In [1]:
import numpy as np

In [11]:
# Задание 1
n = 10
np.arange(n-1,-1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
# ?np.arange

In [15]:
# Задание 2
matrix  = np.diag(np.arange(n-1,-1, -1), k=1)
np.trace(matrix )

0

In [16]:
# Задание 3
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

A = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
B = np.array([4, 12, -3])
X = np.linalg.inv(A).dot(B)
X

array([ 0.46666667,  3.84444444, -5.55555556])

In [19]:
# Задание 4
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
users_stats

array([[2, 1, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 1, 2, 1, 0, 1],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0, 5],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [1, 0, 0, 2, 1, 4]], dtype=int32)

In [22]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

id = 1
min_acr = 2* np.pi
for usr in users_stats:
    cos = np.arccos( cosine( next_user_stats, usr ) ) 
    if cos < min_acr:
        min_acr = cos
        min_isr = id
    id+=1

min_isr, min_acr

1.369438406004566
0.5639426413606291
1.1592794807274087
0.6590580358264091
1.1592794807274087
1.5707963267948966
1.5707963267948966
0.3217505543966423
1.5707963267948966
1.5707963267948966


(8, 0.3217505543966423)